apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-busybox
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend-busybox
  template:
    metadata:
      labels:
        app: backend-busybox
    spec:
      containers:
        - name: busybox
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              while true; do
                echo "Backend Busybox Running";
                sleep 30;
              done
