---
- name: Base setup for all Kubernetes nodes
  hosts: k8s_cluster
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install basic tools
      apt:
        name:
          - curl
          - wget
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
